site:
  title: Kubewarden
  start_page: 1.20@kubewarden:en:introduction.adoc

content:
  sources:
    #- url: https://github.com/rancher/kubewarden-product-docs.git
    - url: ./
      branches: [main]
      start_paths: [shared, docs/next, docs/version-*]

ui:
  bundle:
    url: tmp/sp
    snapshot: true
  supplemental_files: ./kw-community-docs-supp-files

asciidoc:
  attributes:
    kw-build-type: 'community' # 'community' or 'product'
    kw-rancher-product-name: 'SUSE® Rancher Prime Policy Manager'
    kw-community-product-name: 'Kubewarden'
    page-pagination: ''
    tabs-sync-option: ''
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'

output:
  dir: build-community/site
